name: week7_clean_architecture
description: "Campus Notify - Clean Architecture refactor (Week 7)."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  sqflite: ^2.4.4+1
  path: ^1.9.1
  intl: ^0.20.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
